apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: https
      port: 443             # Standard HTTPS port from user's browser
      targetPort: 8080      # Argo CD server container typically listens on 8080
      nodePort: 30002       # Exposed to localhost:30002 # You can change this to any port in the 30000–32767 range