apiVersion: v1
kind: Service
metadata:
  name: python-webapp
  labels:
    app: fastapi
spec:
  type: NodePort
  ports:
    - port: 8081 # Service port
      targetPort: 8081 # Container port
      protocol: TCP
      nodePort: 30003 # This is the port on the each node
  selector:
    app: fastapi